### ISSUE TITLE
Fala brother top d+ seu repositório! Não consegui chegar onde vc chegou, dá olhada no meu repo?

### ISSUE THREAD

**Issue by venelouis** [casjunior93/Projeto-DIO---Trabalhando-com-Machine-Learning-na-Pratica-no-Azure-ML#1]
Este é o link da pasta do meu repositório do desafio aqui eu conto alguns detalhes dos problemas que estou tendo criei até uma "discussão" por causa dele veja no link tbm abaixo:

https://github.com/venelouis/Desafios-dio.me/blob/main/Microsoft%20Azure%20AI%20Fundamentals/Problemas%20com%20o%20Desafio%20de%20Projeto%3A%20Trabalhando%20com%20Machine%20Learning%20na%20Pr%C3%A1tica%20do%20Azure%20ML.md

link da discussão:
https://github.com/venelouis/Desafios-dio.me/discussions/2

E por fim mais uma vez, parabéns seu repositório tá bem bonito. @casjunior93

**Comment by casjunior93** [comment]
Opa, tudo bem? Obrigado pelo elogio. Eu atualizei o Readme com os passos extras pra criar o modelo e o ponto de extremidade. Abraço!

**Comment by venelouis** [comment]
maravilha vou tentar novamente depois
